{{ $parameters := (dict "Release" .Release "Chart" .Chart "Name" "influxdb") }}
{{- $secretValue := (randAlphaNum 16) | b64enc | quote }}
{{- $tokenValue := (randAlphaNum 16) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "green-bench.name" $parameters) ) }}
{{- if $secret }}
{{- $secretValue = index $secret.data "INFLUXDB_PASSWORD" }}
{{- $tokenValue = index $secret.data "INFLUXDB_TOKEN" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "green-bench.name" $parameters }}
  labels:
    {{- include "green-bench.labels" $parameters | nindent 4 }}
data:
  INFLUXDB_PASSWORD: {{ $secretValue }}
  INFLUXDB_TOKEN: {{ $tokenValue }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "green-bench.name" $parameters }}
  labels:
    {{- include "green-bench.labels" $parameters | nindent 4 }}
data:
  influxdb-init.sh: |
{{ .Files.Get "dist/influxdb-init.sh" | indent 4 }}